apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubernetes-gitops-api
  namespace: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: kubernetes-gitops-api

  template:
    metadata: 
      labels:
        app: kubernetes-gitops-api

    spec:
      containers:
      - name: api
        image: kubernetes-gitops-api:1.0.0
        ports:
          - containerPort: 5000