apiVersion: v1 
kind: Service
metadata:
  name: kubernetes-gitops-api
  namespace: dev

spec:
  type: ClusterIP
  selector:
      app: kubernetes-gitops-api
  ports:
   - port: 80
     targetPort: 5000
