name: CI - Esteira de testes

# ao ter um push na main ou pull request na main irá rodar a esteira de testes
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # irá rodar os teste + build da imagem docker
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        working-directory: ./app
        run: pip install -r requirements.txt

      - name: Testar aplicação
        working-directory: ./app
        run: python -m py_compile app.py

      - name: Build da imagem Docker
        run: docker build -t kubernetes-gitops-api:ci ./app

# esta esteira não faz o publish da imagem no docker hub, so faz os testes e builda a imagem  