name: CI - Esteira de testes

# ao ter um novo commit ou pull request na branch main 
on: 
  push: 
    branches:
      - main

  pull_request:
    branches:
      - main

# irá rodar a esteira de CI ( teste + build)
    
jobs:
  test:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      # usamos comando with para "configurações" e run para comandos
      - name: Instalar Dependencias
        working-directory: ./app
        run: pip install -r requirements.txt

      - name: Testar Aplicação
        working-directory: ./app
        run: python -m py_compile app.py

        # como o nome diz, está buildando a imagem docker
      - name: Build da imagem docker
        run: docker build -t diegomelodevops/kubernetes-gitops-api:1.2.0 ./app
        # aqui estamos fazendo o login para que possamos fazer o push
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        # as credenciais ficam armazenadas nas secrets do github actions para
        # não ficar hardcoded
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
        # iremos subir a imagem para o repositorio do docker hub
      - name: Push da imagem para Docker Hub
        run: docker push diegomelodevops/kubernetes-gitops-api:1.2.0