name: Release 

# quando houver uma mudança na tag irá rodar a esteira de testes + build + push da imagem no docker hub
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    # criando uma variavel para não ter que ficar repetindo o nome do repositorio
    env:
      REGISTRY_IMAGE: diegomelodevops/kubernetes-gitops-api

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

        # aqui é aonde irá ser feito a automação da versão da imagem e 
        # retirar a letra v da tag para deixar ex "1.3.0" ao inves de ter o "v"
        # e quebrar o build da imagem docker
      - name: Definir versão da imagem
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "Versão definida: ${VERSION}"

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        working-directory: ./app
        run: pip install -r requirements.txt

      - name: Testar aplicação
        working-directory: ./app
        run: python -m py_compile app.py

      - name: Build da imagem Docker
        run: docker build -t ${{ env.REGISTRY_IMAGE }}:${{ env.VERSION }} ./app
        
        # para fazer o publish da imagem precisamos logar no docker hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          # aqui está puxando as secrets armazenada no repository secrets do github são
          # as credencias de acesso para acessar e poder na etapa seguinte fazer o push da imagem
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ env.REGISTRY_IMAGE }}:${{ env.VERSION }}

# esta esteira faz o publish da imagem no docker hub, testa + build + automação da versão da tag + e sobre pro docker hub